export enum WebsiteEvent {
    WELCOME = "WELCOME",
    MENU_PRICES = "MENU_PRICES",
    OUR_STORY = "OUR_STORY",
    REFER_FRIEND = "REFER_FRIEND",
    SIGNIN = "SIGNIN",
    FORGOT_PASSWORD = "FORGOT_PASSWORD",
    RESET_PASSWORD = "RESET_PASSWORD",
    CREATE_ACCOUNT = "CREATE_ACCOUNT",
    CHECKOUT = "CHECKOUT",
    START_COOKING = "START_COOKING",
    ORDER_HISTORY = "ORDER_HISTORY",
    ORDER_INFO = "ORDER_INFO"
}

export enum RecipeEvent {
    ENTER = "ENTER",
    EXIT = "EXIT"
}